In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
np.array([10.0,20])

array([10., 20.])

In [5]:
x=np.array([10.5,22,45.45,45])

In [6]:
print(x)

[10.5  22.   45.45 45.  ]


In [11]:
%timeit np.arange(10)

947 ns ± 11.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [13]:
x.ndim

1

In [14]:
x.shape

(4,)

In [24]:
a=np.array([[1,2,3],[3,5,6]])

In [25]:
a.ndim

2

In [26]:
a.size

6

In [27]:
a.shape

(2, 3)

In [28]:
len(a)

2

In [42]:
z=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [43]:
z.ndim

3

In [44]:
z.shape

(2, 2, 2)

In [45]:
z.size

8

In [46]:
np.linspace(1,100,6)

array([  1. ,  20.8,  40.6,  60.4,  80.2, 100. ])

In [47]:
np.arange(1,100,6)

array([ 1,  7, 13, 19, 25, 31, 37, 43, 49, 55, 61, 67, 73, 79, 85, 91, 97])

In [48]:
np.ones(4)

array([1., 1., 1., 1.])

In [49]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [50]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [51]:
np.eye(2,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [54]:
np.random.rand(4)  #randn with negative values

array([0.87764816, 0.72560211, 0.75248071, 0.77559917])

In [56]:
z.dtype

dtype('int32')

In [60]:
np.array([1+2j,3+2j])

array([1.+2.j, 3.+2.j])

In [62]:
np.diag([3,4,5,66,6])  

array([[ 3,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  5,  0,  0],
       [ 0,  0,  0, 66,  0],
       [ 0,  0,  0,  0,  6]])

In [63]:
 #list input to most of the functions including this

In [68]:
a=np.array([2,4,5,6])

In [69]:
b=a

In [70]:
np.shares_memory(a,b)   

True

In [71]:
#Views hence pooint to same since memory efficient

In [72]:
y=np.arange(2).copy()

In [73]:
#mask functions separate the values

In [74]:
y+1

array([1, 2])

In [76]:
np.array_equal(y,z)

False

In [79]:
np.sin([989])

array([0.56603309])